//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheques
    {
        public int Cod_Cheques { get; set; }
        public string Cod_Banco { get; set; }
        public string Cod_Sucursal { get; set; }
        public string Cod_Postal { get; set; }
        public string Num_Cheque { get; set; }
        public string Num_Cuenta { get; set; }
        public Nullable<int> Cod_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Entrada { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
        public Nullable<float> Importe { get; set; }
        public string CUIT_Cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Vec { get; set; }
        public string Obs_Salida { get; set; }
        public Nullable<System.DateTime> FechaAnulSal { get; set; }
        public string ObserAnulSal { get; set; }
        public Nullable<System.DateTime> FechaAnulEnt { get; set; }
        public string ObserAnulEnt { get; set; }
    }
}
