//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidades
    {
        public string Cod_Localidad { get; set; }
        public string Desc_Localidad { get; set; }
        public string Cod_Provincia { get; set; }
        public string C_Postal { get; set; }
    }
}
