//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class ChequeEntidades : DbContext
    {
        public ChequeEntidades()
            : base("name=ChequeEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bancos> bancos { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<localidades> localidades { get; set; }
        public DbSet<provincias> provincias { get; set; }
        public DbSet<zonas> zonas { get; set; }
        public DbSet<viajantes> viajantes { get; set; }
        public DbSet<viajantes_view> viajantes_view { get; set; }
        public DbSet<clientes_view> clientes_view { get; set; }
        public DbSet<cheques> cheques { get; set; }
    }
}
